### ISSUE TITLE
Is there any free surface option

### ISSUE THREAD

**Issue by xichaoqiang** [gaia-up/shotwavemod#1]
Is there any free surface option in the package?

**Comment by gaia-up** [comment]
Yes, you may custom in parameter file (.par). For instance, seismic2dfdm.par in row 34 (increase value for more absorption) and row 36 (activate or deactivate surface multiple).

**Comment by xichaoqiang** [comment]
Thanks for your reply.If I set the row 36 is 0, free surface is applied?

**Comment by gaia-up** [comment]
In Row 36:
Set 1 to activate surface multiple
Set 0 to deactivate surface multiple

**Comment by xichaoqiang** [comment]
If I want get rayleigh wave in the simulation result.Which one should I set?

**Comment by gaia-up** [comment]
At moment the program only accommodate compressional body wave (P-Wave).

**Comment by xichaoqiang** [comment]
OK.Thanks for your reply.It is very kind of you.

**Comment by gaia-up** [comment]
You are welcome
